GCT_V01/urls.py
from django.contrib import admin
from django.urls import path, re_path
from tifert import views
################################################
from django.conf import settings
from django.conf.urls.static import static
###########################################
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views
################################################

urlpatterns = [

##############################################################
    path('signup/', accounts_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),



###############################################################
    path('', views.home, name='home'),
    ###################################
    # ex: /tifert/
    path('tabia/', views.index_tabia, name='index_tabia'),
    # ex: /tifert/5/
    re_path(r'^new_tabia/$', views.NewPostView.as_view(), name='new_tabia'),
    # ex: /tifert/5/
    re_path(r'^tabia/table/(?P<pk>\d+)/$', views.table_tabia, name='table_tabia'),
    re_path(r'^tabia/table/(?P<pk>\d+)/edit/$',views.DefUpdateView.as_view(), name='edit_tabia'),

    # ex: /tifert/5/results/
    ###################################
    # ex: /rapport/
    path('rj/', views.index_rj, name='index_rj'),
    re_path(r'^new_rj/$', views.NewRjView.as_view(), name='new_rj'),
    # ex: /tifert/5/
    re_path(r'^rj/table/(?P<pk>\d+)/$', views.table_rj, name='table_rj'),
    re_path(r'^rj/table/(?P<pk>\d+)/edit/$',views.RjUpdateView.as_view(), name='edit_rj'),


    ##########################################################

    path('upload/', views.image_upload, name='upload'),
    path('photo_list/', views.photo_list, name='photo_list'),
    #############################################################

    path('calcule/', views.calcule, name='calcule'),
########################################################
    re_path(r'^search/$', views.search, name='search'),
    re_path(r'^def_search/$', views.def_search, name='def_search'),
    re_path(r'^Rj_search/$', views.Rj_search, name='Rj_search'),
    ############################################################
    #                    PDF CREATION
    ############################################################
    path('pdf/', views.some_view, name='pdf'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tifert/models.py
from django.db import models

# Create your models here.


from django.utils import timezone
###################################################
from django.db import models
from django.utils.text import Truncator
from django.contrib.auth.models import User


DEFAUT_STATUS = (
    ('Mécanique', 'Mécanique'),
    ('Q_Gypse', 'Qualité de Gypse'),
    ('Eléctrique', 'Eléctrique'),
)

TYPE_OBGJET = (
    ('Vap', 'Vapeur'),
    ('Reclamtion', 'Reclamtion'),
    ('Transfert', 'Transfert'),
)



##############################Rapport journalier de Tifert vers GCT##########################################

class Rj(models.Model):
    date = models.DateTimeField(default=timezone.now,verbose_name="DATE")
###################################################################################
    h_m_h2so4 = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="heure de marche sulfurique")
    fqh_p_h2so4 = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="FQ (j-1) production")
    fqa_p_h2so4 = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="FQ (j) production")
    p_acide_h2so4 = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Production H2SO4")
    sh_acide_h2so4 = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Stock H2SO4 (j-1)")
    tk2_1 =  models.DecimalField(max_digits=8, decimal_places=2, verbose_name="7560 TK2/1 (T)")
    tk2_2 =  models.DecimalField(max_digits=8, decimal_places=2, verbose_name="7560 TK2/2 (T)")
    titre_p_h2so4 = models.DecimalField(max_digits=4, decimal_places=4, verbose_name="Titre H2SO4 produit")


    sh_s = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Stock Soufre (j-1)")
    sa_s = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Stock Soufre (j)")
    s_c = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Soufre consommé")
    p_s_liq = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Prod soufre liquide")
    r_s_solid = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Reception soufre solide")
    tk1_1 =  models.DecimalField(max_digits=8, decimal_places=2, verbose_name="7530 TK1/1 (T)")
    tk1_2 =  models.DecimalField(max_digits=8, decimal_places=2, verbose_name="7530 TK1/2 (T)")

    fqd_t_h2so4 = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="FQ tr(début)")
    fqf_t_h2so4 = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="FQ tr(fin)")
    t_acide_h2so4 = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="transfert H2SO4")
    titre_t_h2so4 = models.DecimalField(max_digits=4, decimal_places=4, verbose_name="Titre H2SO4 produit")


    p_acide_h3po4 = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Production H3PO4 (T)")
    h_a_gypse = models.DecimalField(max_digits=4, decimal_places=2, verbose_name="Arrêt tabia (heure,minute)")





    last_updated = models.DateTimeField(auto_now_add=True)
    starter = models.ForeignKey(User,on_delete=models.CASCADE, related_name='starters')
    class Meta:
        verbose_name = "Rj"
        ordering = ['-date']


    def __str__(self):
        """
        Cette méthode que nous définirons dans tous les modèles
        nous permettra de reconnaître facilement les différents objets que
        nous traiterons plus tard dans l'administration
        """
        #return self.journee
        return "{0}".format(self.date)





#####################################################################################
################################Defaut_tabia#######################################################
  ##################################################################################
class Defaut_tabia(models.Model):


    defaut = models.CharField(max_length=10, choices=DEFAUT_STATUS)
    h_a_tabia = models.DecimalField(max_digits=4, decimal_places=2, verbose_name="Arrêt tabia(Heure,min)")
    message = models.TextField()
    jour = models.ForeignKey(Rj,on_delete=models.CASCADE, related_name='jours')
    doc = models.FileField(upload_to='Documents/tabia/%Y/%m/%d/')



    class Meta:
        verbose_name = "Defaut_tabia"
        ordering = ['-jour']




    def __str__(self):
        """
        Cette méthode que nous définirons dans tous les modèles
        nous permettra de reconnaître facilement les différents objets que
        nous traiterons plus tard dans l'administration
        """
        #return self.journee
        return "{0}".format(self.defaut)



#####################################################################################
################################Defaut_tabia#######################################################
  ##################################################################################
class Fax(models.Model):



    date = models.DateTimeField(default=timezone.now,verbose_name="DATE")

    objet = models.CharField(max_length=10, choices=TYPE_OBGJET)
    text = models.CharField(max_length=200)

    fax = models.FileField(upload_to='Documents/fax/%Y/%m/%d/')
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='users')




    class Meta:
        verbose_name = "Fax"
        ordering = ['-date']




    def __str__(self):
        """
        Cette méthode que nous définirons dans tous les modèles
        nous permettra de reconnaître facilement les différents objets que
        nous traiterons plus tard dans l'administration
        """
        #return self.journee
        return "{0}".format(self.text)


########################################""gallerie photo########################

class Photo(models.Model):
    description = models.CharField(max_length=255, blank=True)
    file = models.ImageField(upload_to='Documents/images/%Y/%m/%d/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'photo'
        verbose_name_plural = 'photos'
        ordering = ['-uploaded_at']

tifert/forms.py
from PIL import Image
from django import forms
from django.core.files import File
from .models import Photo



#from django import forms
from .models import Rj
from .models import Defaut_tabia

from decimal import Decimal

#from .models import Document,Defaut_tabia

#class DocumentForm(forms.ModelForm):
    # class Meta:
    #    model = Document
    #    fields = ('description', 'document', )

class NewRjForm(forms.ModelForm):
    #message = forms.CharField(widget=forms.Textarea(), max_length=4000)

    class Meta:
        model = Rj
        fields = ['date', 'h_m_h2so4','fqh_p_h2so4','fqa_p_h2so4','p_acide_h2so4','sh_acide_h2so4','tk2_1','tk2_2',
        'titre_p_h2so4','sh_s','sa_s','s_c','p_s_liq','r_s_solid','tk1_1','tk1_2','fqd_t_h2so4',
        'fqf_t_h2so4','t_acide_h2so4','titre_t_h2so4','p_acide_h3po4','h_a_gypse']

    def clean(self):

        cleaned_data = super(NewRjForm, self).clean()
        fqh_p_h2so4 = cleaned_data.get("fqh_p_h2so4")
        fqa_p_h2so4 = cleaned_data.get("fqa_p_h2so4")


        if fqh_p_h2so4 > fqa_p_h2so4:
            msg = u"FQ(j) doit être plus élevé que FQ(j-1)"
            self._errors['fqh_p_h2so4'] = self.error_class([msg])

        return cleaned_data






########################################################
class ImageForm(forms.ModelForm):
     class Meta:
        model = Photo
        fields = ('description', 'file', )
##################################################
class NewtabiaForm(forms.ModelForm):
    class Meta:
        model = Defaut_tabia
        fields = ('defaut', 'h_a_tabia','message','jour','doc',)

########################################################
class PhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Photo
        fields = ('file', 'x', 'y', 'width', 'height', )

    def save(self):
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.file.path)

        return photo

templates/Rj_list.html
{% extends 'base.html' %}

{% block content %}
  <form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
  </form>
  <ul>
  {% for user in filter.qs %}
    <li>{{ user.date.date }} - {{ user.p_acide_h2so4 }}</li>
  {% endfor %}
  </ul>
{% endblock %}

templates/acceuil.html
{% extends 'base.html' %}

{% block breadcrumb %}

{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">

    </thead>
    <tbody>
      <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
      <div class="row" style="margin-top: 20px">

        <div class="col-sm-4 col-md-3">
          <img src="{{ photos.document.url }}" class="thumbnail">
        </div>


    </tbody>
  </table>
{% endblock %}

templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}SERVICES LIES A TIFERT{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link href="{% static 'css/cropper.css' %}" rel="stylesheet">
     {% block stylesheet %}{% endblock %}
  </head>
  {% block body %}

  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">

    <a class="navbar-brand" href="{% url 'home' %}">SERVICES LIES A TIFERT</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
           <div class="collapse navbar-collapse" id="mainMenu">
            {% if user.is_authenticated %}
               <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>
             <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
              <a class="dropdown-item" href="#">My account</a>
              <a class="dropdown-item" href="#">Change password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
              </div>
          </li>
        </ul>
      {% else %}
        <form class="form-inline ml-auto">
          <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
          <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
        </form>
      {% endif %}
    </div>
  </div>
</nav>
        <ol class="breadcrumb my-4">
        {% block breadcrumb %}

        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
</div>
  {% endblock body %}

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
<script src="{% static 'js/cropper.js' %}"></script>

{% block javascript %}
{% endblock %}
    </body>
</html>

templates/base1.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Simple is Better Than Complex{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="{% static 'css/cropper.min.css' %}" rel="stylesheet">
    <style type="text/css">
      .page-header {
        margin-top: 0;
      }
    </style>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/cropper.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home' %}">SERVICES LIES A TIFERT</a>
      <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

templates/calc.html
{% extends 'base.html' %}

{% block breadcrumb %}
<li class="breadcrumb-item active"><a href="{% url 'home'%}">Accueil</a></li>
<li class="breadcrumb-item active"><a href="{% url 'index_rj'%}">TIFERT_R_J</a></li>
{% endblock %}

{% block content %}
<div class="container-fluid">
<!--  <div class="row justify-content-md-center">-->
<div class="mb-4">
    <a href="{% url 'new_rj' %}" class="btn btn-primary">Nouveau Rapport</a>
  </div>

  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>

        <th>Total Prod Acide (T)</th>

      </tr>
    </thead>
    <tbody>

        <tr>
          <td><a href="#">{{ Rjsomme.p_acide_h2so4__sum }}</a></td>


        </tr>

    </tbody>
  </table>

{% endblock %}

templates/def_list.html
{% extends 'base.html' %}

{% block content %}
  <form method="get">
    {{ filter.form.as_ul}}
    <button type="submit">Search</button>
  </form>
  <ul>
  {% for def in filter.qs %}
    <li>{{ def.defaut}} - {{ def.h_a_tabia }}</li>
  {% endfor %}
  </ul>
{% endblock %}

templates/login.html
{% extends 'base_accounts.html' %}

{% block title %}Log in to SERVICES LIES A TIFERT{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Log in</h3>
          <form method="post" novalidate>
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-primary btn-block">Log in</button>
  </form>
        </div>
        <div class="card-footer text-muted text-center">
          New to Django Boards? <a href="{% url 'signup' %}">Sign up</a>
        </div>
      </div>
      <div class="text-center py-2">
        <small>
          <a href="#" class="text-muted">Forgot your password?</a>
        </small>
      </div>
    </div>
  </div>
{% endblock %}

templates/photo_list.html
{% extends 'base.html' %}

{% block javascript %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_file").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock %}

{% block content %}
  <h1 class="page-header">Album</h1>

  <!-- FORM TO UPLOAD THE IMAGES -->
  <form method="post" enctype="multipart/form-data" id="formUpload">
    {% csrf_token %}
    {{ form }}
  </form>

  <!-- MODAL TO CROP THE IMAGE -->
  <div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
          <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
        </div>
      </div>
    </div>
  </div>

  <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
  <div class="row" style="margin-top: 20px">
    {% for photo in photos %}
      <div class="col-sm-4 col-md-3">
        <img src="{{ photo.file.url }}" class="thumbnail">
      </div>
    {% endfor %}
  </div>

{% endblock %}

templates/signup.html
{% extends 'base_accounts.html' %}

{% block title %}Sign up to SERVICES LIES A TIFERT{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Sign up</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Create an account</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          Already have an account? <a href="{% url 'login' %}">Log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/user_list.html
{% extends 'base.html' %}

{% block content %}
  <form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
  </form>
  <ul>
  {% for user in filter.qs %}
    <li>{{ user.username }} - {{ user.get_full_name }}</li>
  {% endfor %}
  </ul>
{% endblock %}